const nodes = {
    nodes:
    [
    {
        id: "001",
        text: "The wait for election results feels like forever.",
        public_metrics: {
        likes: 37,
        reply: 374,
        retweet: 1,
        quote: 63,
        },
        influence: 475,
        "geo_location": "India",
    },
    {
        id: "002",
        text: "BREAKING: Trump sues election officials over disputed ballot counts. #Election2024 #TrumpSues",
        public_metrics: {
        likes: 295,
        reply: 96,
        retweet: 117,
        quote: 1,
        },
        influence: 509,
        "geo_location": "Malaysia",
    },
    {
        id: "003",
        text: "Social media platforms are under fire for failing to curb disinformation during the election. #Disinformation #Election2024",
        public_metrics: {
        likes: 268,
        reply: 108,
        retweet: 184,
        quote: 99,
        },
        influence: 659,
        "geo_location": "Malaysia",
    },
    {
        id: "004",
        text: "Trump blames mainstream media for unfair coverage of his campaign. #FakeNews #Trump2024",
        public_metrics: {
        likes: 274,
        reply: 57,
        retweet: 43,
        quote: 71,
        },
        influence: 445,
        "geo_location": "Brazil",
    },
    {
        id: "005",
        text: "Early voting surges across the country as tensions rise over election security. #Election2024 #EarlyVoting",
        public_metrics: {
        likes: 395,
        reply: 424,
        retweet: 6,
        quote: 43,
        },
        influence: 868,
        "geo_location": "Canada",
    },
    {
        id: "006",
        text: "Kamala Harris pushes for Medicare for All in her latest policy outline. #HealthcareReform #Harris2024",
        public_metrics: {
        likes: 42,
        reply: 28,
        retweet: 160,
        quote: 30,
        },
        influence: 260,
        "geo_location": "France",
    },
    {
        id: "007",
        text: "The 2024 election is shaping up to be one of the most contentious in US history. #USPolitics",
        public_metrics: {
        likes: 235,
        reply: 244,
        retweet: 71,
        quote: 87,
        },
        influence: 637,
        "geo_location": "Canada",
    },
    {
        id: "008",
        text: "New revelations about election interference efforts shake confidence in democratic process. #Election2024 #ElectionInterference",
        public_metrics: {
        likes: 472,
        reply: 399,
        retweet: 173,
        quote: 77,
        },
        influence: 1121,
        "geo_location": "United Kingdom",
    },
    {
        id: "009",
        text: "Voting machine glitches spark outrage as voters demand answers. #Election2024 #VotingIssues",
        public_metrics: {
        likes: 283,
        reply: 207,
        retweet: 92,
        quote: 20,
        },
        influence: 602,
        "geo_location": "Canada",
    },
    {
        id: "010",
        text: "Debate over mail-in ballots intensifies as election approaches. #MailInBallots #Election2024",
        public_metrics: {
        likes: 191,
        reply: 93,
        retweet: 117,
        quote: 17,
        },
        influence: 418,
        "geo_location": "United States",
    },
    {
        id: "011",
        text: "It's inspiring to see so many people engaged in the process.",
        public_metrics: {
        likes: 422,
        reply: 75,
        retweet: 135,
        quote: 95,
        },
        influence: 727,
        "geo_location": "Canada",
    },
    {
        id: "012",
        text: "Kamala Harris hits the campaign trail with renewed energy, promising economic reform. #Harris2024",
        public_metrics: {
        likes: 498,
        reply: 154,
        retweet: 195,
        quote: 36,
        },
        influence: 883,
        "geo_location": "Japan",
    },
    {
        id: "013",
        text: "Trump promises to slash taxes for middle-class Americans in his latest campaign speech. #Trump2024 #TaxCuts",
        public_metrics: {
        likes: 280,
        reply: 52,
        retweet: 196,
        quote: 84,
        },
        influence: 612,
        "geo_location": "Australia",
    },
    {
        id: "014",
        text: "It's hard to trust the polls after last time.",
        public_metrics: {
        likes: 475,
        reply: 122,
        retweet: 195,
        quote: 14,
        },
        influence: 806,
        "geo_location": "Brazil",
    },
    {
        id: "015",
        text: "Kamala Harris fires back at critics questioning her experience. #Harris2024 #USPolitics",
        public_metrics: {
        likes: 355,
        reply: 324,
        retweet: 152,
        quote: 16,
        },
        influence: 847,
        "geo_location": "France",
    },
    {
        id: "016",
        text: "Fact checkers are working overtime as fake news spreads rapidly during the election season. #FactCheck",
        public_metrics: {
        likes: 448,
        reply: 217,
        retweet: 33,
        quote: 90,
        },
        influence: 788,
        "geo_location": "Australia",
    },
    {
        id: "017",
        text: "BREAKING: US Postal Service sees delays as millions vote by mail. #MailInVoting #Election2024",
        public_metrics: {
        likes: 77,
        reply: 431,
        retweet: 1,
        quote: 87,
        },
        influence: 596,
        "geo_location": "Germany",
    },
    {
        id: "018",
        text: "The election results are making me nervous.",
        public_metrics: {
        likes: 75,
        reply: 224,
        retweet: 8,
        quote: 9,
        },
        influence: 316,
        "geo_location": "Malaysia",
    },
    {
        id: "019",
        text: "New Harris ad campaign targets suburban voters in swing states. #HarrisForThePeople",
        public_metrics: {
        likes: 109,
        reply: 152,
        retweet: 52,
        quote: 74,
        },
        influence: 387,
        "geo_location": "Japan",
    },
    {
        id: "020",
        text: "Trump vows to continue his fight against the 'deep state'. #Trump2024 #USPolitics",
        public_metrics: {
        likes: 415,
        reply: 139,
        retweet: 158,
        quote: 55,
        },
        influence: 767,
        "geo_location": "Japan",
    },
    {
        id: "021",
        text: "Trump accuses Kamala Harris of hiding key policy details. #TrumpVsHarris #Election2024",
        public_metrics: {
        likes: 431,
        reply: 469,
        retweet: 92,
        quote: 6,
        },
        influence: 998,
        "geo_location": "India",
    },
    {
        id: "022",
        text: "Election night coverage will feature new real-time polling data from key battleground states. #ElectionNight2024",
        public_metrics: {
        likes: 61,
        reply: 205,
        retweet: 31,
        quote: 29,
        },
        influence: 326,
        "geo_location": "Malaysia",
    },
    {
        id: "023",
        text: "Kamala Harris speaks out against Trump\u2019s immigration policies, promising reform. #Harris2024 #Immigration",
        public_metrics: {
        likes: 216,
        reply: 302,
        retweet: 1,
        quote: 94,
        },
        influence: 613,
        "geo_location": "United Kingdom",
    },
    {
        id: "024",
        text: "I can't take my eyes off the election updates.",
        public_metrics: {
        likes: 179,
        reply: 59,
        retweet: 71,
        quote: 36,
        },
        influence: 345,
        "geo_location": "United Kingdom",
    },
    {
        id: "025",
        text: "BREAKING: Hackers target US election infrastructure, sparking security concerns. #ElectionSecurity",
        public_metrics: {
        likes: 231,
        reply: 479,
        retweet: 114,
        quote: 79,
        },
        influence: 903,
        "geo_location": "India",
    },
    {
        id: "026",
        text: "Election analysts warn of possible voting irregularities in key states. #Election2024",
        public_metrics: {
        likes: 444,
        reply: 67,
        retweet: 159,
        quote: 65,
        },
        influence: 735,
        "geo_location": "Brazil",
    },
    {
        id: "027",
        text: "The early voting numbers were record-breaking!",
        public_metrics: {
        likes: 60,
        reply: 121,
        retweet: 111,
        quote: 85,
        },
        influence: 377,
        "geo_location": "Malaysia",
    },
    {
        id: "028",
        text: "My whole family is glued to the TV waiting for results.",
        public_metrics: {
        likes: 66,
        reply: 170,
        retweet: 0,
        quote: 6,
        },
        influence: 242,
        "geo_location": "Brazil",
    },
    {
        id: "029",
        text: "I've never been so anxious about an election before.",
        public_metrics: {
        likes: 429,
        reply: 411,
        retweet: 107,
        quote: 88,
        },
        influence: 1035,
        "geo_location": "Malaysia",
    },
    {
        id: "030",
        text: "We need change, and I hope this election brings it.",
        public_metrics: {
        likes: 175,
        reply: 403,
        retweet: 41,
        quote: 97,
        },
        influence: 716,
        "geo_location": "United Kingdom",
    },
    {
        id: "031",
        text: "BREAKING: Trump claims voting machines are being tampered with, provides no evidence. #ElectionSecurity #TrumpClaims",
        public_metrics: {
        likes: 72,
        reply: 69,
        retweet: 3,
        quote: 61,
        },
        influence: 205,
        "geo_location": "India",
    },
    {
        id: "032",
        text: "This is such a nail-biting election.",
        public_metrics: {
        likes: 37,
        reply: 352,
        retweet: 53,
        quote: 14,
        },
        influence: 456,
        "geo_location": "France",
    },
    {
        id: "033",
        text: "It's amazing to see so many first-time voters!",
        public_metrics: {
        likes: 222,
        reply: 332,
        retweet: 33,
        quote: 70,
        },
        influence: 657,
        "geo_location": "Malaysia",
    },
    {
        id: "034",
        text: "I hope everyone stays safe during this election period.",
        public_metrics: {
        likes: 117,
        reply: 91,
        retweet: 65,
        quote: 81,
        },
        influence: 354,
        "geo_location": "France",
    },
    {
        id: "035",
        text: "Kamala Harris pushes for increased gun control measures, sparking heated debates online. #Harris2024",
        public_metrics: {
        likes: 391,
        reply: 494,
        retweet: 154,
        quote: 89,
        },
        influence: 1128,
        "geo_location": "Australia",
    },
    {
        id: "036",
        text: "Trump calls for immediate recount in key battleground states. #ElectionRecount #Trump2024",
        public_metrics: {
        likes: 81,
        reply: 97,
        retweet: 45,
        quote: 77,
        },
        influence: 300,
        "geo_location": "United Kingdom",
    },
    {
        id: "037",
        text: "BREAKING: Election turnout reaches historic levels, especially among young voters. #Election2024 #VoterTurnout",
        public_metrics: {
        likes: 140,
        reply: 426,
        retweet: 142,
        quote: 95,
        },
        influence: 803,
        "geo_location": "United States",
    },
    {
        id: "038",
        text: "Donald Trump says he'll challenge any election result he doesn't like. #Election2024",
        public_metrics: {
        likes: 489,
        reply: 306,
        retweet: 129,
        quote: 82,
        },
        influence: 1006,
        "geo_location": "Brazil",
    },
    {
        id: "039",
        text: "I just cast my vote, feeling hopeful.",
        public_metrics: {
        likes: 5,
        reply: 29,
        retweet: 106,
        quote: 52,
        },
        influence: 192,
        "geo_location": "Canada",
    },
    {
        id: "040",
        text: "BREAKING: Long lines reported at polling stations nationwide. #Election2024 #VoteNow",
        public_metrics: {
        likes: 491,
        reply: 261,
        retweet: 114,
        quote: 72,
        },
        influence: 938,
        "geo_location": "Brazil",
    },
    {
        id: "041",
        text: "I really hope the right candidate wins.",
        public_metrics: {
        likes: 396,
        reply: 84,
        retweet: 0,
        quote: 14,
        },
        influence: 494,
        geo_location: "Japan",
    },
    {
        id: "042",
        text: "Can't wait to see the results tonight.",
        public_metrics: {
        likes: 433,
        reply: 466,
        retweet: 119,
        quote: 48,
        },
        influence: 1066,
        geo_location: "Germany",
    },
    {
        id: "043",
        text: "New polls show Trump leading in key swing states. Could this mean a comeback? #Election2024 #Trump2024",
        public_metrics: {
        likes: 485,
        reply: 456,
        retweet: 152,
        quote: 28,
        },
        influence: 1121,
        geo_location: "Germany",
    },
    {
        id: "044",
        text: "The debates were so intense this year!",
        public_metrics: {
        likes: 346,
        reply: 466,
        retweet: 51,
        quote: 21,
        },
        influence: 884,
        geo_location: "India",
    },
    {
        id: "045",
        text: "The future of the country is in our hands.",
        public_metrics: {
        likes: 133,
        reply: 336,
        retweet: 88,
        quote: 40,
        },
        influence: 597,
        geo_location: "Brazil",
    },
    {
        id: "046",
        text: "I can't believe this is happening!",
        public_metrics: {
        likes: 128,
        reply: 249,
        retweet: 185,
        quote: 92,
        },
        influence: 654,
        geo_location: "United Kingdom",
    },
    {
        id: "047",
        text: "I'm so proud of everyone who went out to vote!",
        public_metrics: {
        likes: 484,
        reply: 154,
        retweet: 39,
        quote: 16,
        },
        influence: 693,
        geo_location: "France",
    },
    {
        id: "048",
        text: "As election day approaches, campaigns ramp up their efforts to mobilize voters. #Election2024",
        public_metrics: {
        likes: 403,
        reply: 493,
        retweet: 198,
        quote: 15,
        },
        influence: 1109,
        geo_location: "Canada",
    },
    {
        id: "049",
        text: "I can't stop refreshing the election updates.",
        public_metrics: {
        likes: 21,
        reply: 288,
        retweet: 127,
        quote: 58,
        },
        influence: 494,
        geo_location: "Japan",
    },
    {
        id: "050",
        text: "This is such a pivotal moment in history.",
        public_metrics: {
        likes: 256,
        reply: 414,
        retweet: 177,
        quote: 61,
        },
        influence: 908,
        geo_location: "Brazil",
    },
    {
        id: "051",
        text: "Did Kamala Harris really call for abolishing the electoral college? Fact or fiction? #USPolitics #FactCheck2024",
        public_metrics: {
        likes: 471,
        reply: 345,
        retweet: 164,
        quote: 28,
        },
        influence: 1008,
        geo_location: "Australia",
    },
    {
        id: "052",
        text: "Harris slams Trump\u2019s handling of the pandemic as reckless and dangerous. #Harris2024 #COVID19Response",
        public_metrics: {
        likes: 237,
        reply: 456,
        retweet: 95,
        quote: 58,
        },
        influence: 846,
        geo_location: "Malaysia",
    },
    {
        id: "053",
        text: "Protesters clash over new voting regulations as election day nears. #VoterRights #USPolitics",
        public_metrics: {
        likes: 22,
        reply: 254,
        retweet: 80,
        quote: 27,
        },
        influence: 383,
        geo_location: "Japan",
    },
    {
        id: "054",
        text: "Donald Trump insists he is the 'law and order' candidate. #Trump2024",
        public_metrics: {
        likes: 33,
        reply: 479,
        retweet: 43,
        quote: 38,
        },
        influence: 593,
        geo_location: "Germany",
    },
    {
        id: "055",
        text: "Fact check: Trump's claim about record unemployment is misleading. #FactCheck2024 #Election2024",
        public_metrics: {
        likes: 423,
        reply: 287,
        retweet: 85,
        quote: 59,
        },
        influence: 854,
        geo_location: "France",
    },
    {
        id: "056",
        text: "This election feels so different from previous years.",
        public_metrics: {
        likes: 372,
        reply: 421,
        retweet: 86,
        quote: 69,
        },
        influence: 948,
        geo_location: "United Kingdom",
    },
    {
        id: "057",
        text: "Election day feels like a rollercoaster!",
        public_metrics: {
        likes: 224,
        reply: 299,
        retweet: 56,
        quote: 48,
        },
        influence: 627,
        geo_location: "Germany",
    },
    {
        id: "058",
        text: "Trump proposes a new national security plan amid growing tensions with China. #NationalSecurity #Trump2024",
        public_metrics: {
        likes: 238,
        reply: 435,
        retweet: 87,
        quote: 15,
        },
        influence: 775,
        geo_location: "Germany",
    },
    {
        id: "059",
        text: "This is such an important time for our democracy.",
        public_metrics: {
        likes: 441,
        reply: 387,
        retweet: 181,
        quote: 59,
        },
        influence: 1068,
        geo_location: "Australia",
    },
    {
        id: "060",
        text: "Kamala Harris caught in a scandal? Some are calling the recent news a 'distraction' tactic. #Harris2024 #USPolitics",
        public_metrics: {
        likes: 315,
        reply: 21,
        retweet: 143,
        quote: 58,
        },
        influence: 537,
        geo_location: "Australia",
    },
    {
        id: "061",
        text: "The news coverage is overwhelming today.",
        public_metrics: {
        likes: 401,
        reply: 403,
        retweet: 1,
        quote: 11,
        },
        influence: 816,
        geo_location: "Canada",
    },
    {
        id: "062",
        text: "I can't believe the voter turnout this year!",
        public_metrics: {
        likes: 105,
        reply: 238,
        retweet: 170,
        quote: 78,
        },
        influence: 591,
        geo_location: "France",
    },
    {
        id: "063",
        text: "No matter who wins, I hope we can move forward together.",
        public_metrics: {
        likes: 486,
        reply: 284,
        retweet: 48,
        quote: 9,
        },
        influence: 827,
        geo_location: "India",
    },
    {
        id: "064",
        text: "BREAKING: Kamala Harris announces sweeping healthcare reforms ahead of election. #VoteForHarris",
        public_metrics: {
        likes: 247,
        reply: 249,
        retweet: 60,
        quote: 16,
        },
        influence: 572,
        geo_location: "France",
    },
    {
        id: "065",
        text: "Harris announces plans to make college more affordable if elected. #Harris2024 #Education",
        public_metrics: {
        likes: 324,
        reply: 228,
        retweet: 88,
        quote: 57,
        },
        influence: 697,
        geo_location: "United Kingdom",
    },
    {
        id: "066",
        text: "Disinformation experts say the election could be 'won or lost' on social media. #Election2024",
        public_metrics: {
        likes: 358,
        reply: 270,
        retweet: 61,
        quote: 79,
        },
        influence: 768,
        geo_location: "India",
    },
    {
        id: "067",
        text: "I can't believe the polls are so tight.",
        public_metrics: {
        likes: 452,
        reply: 270,
        retweet: 191,
        quote: 84,
        },
        influence: 997,
        geo_location: "Japan",
    },
    {
        id: "068",
        text: "Harris advocates for expanding voting rights protections in her latest town hall event. #Harris2024 #VotingRights",
        public_metrics: {
        likes: 370,
        reply: 381,
        retweet: 58,
        quote: 94,
        },
        influence: 903,
        geo_location: "Japan",
    },
    {
        id: "069",
        text: "This is the most important election of our lifetime.",
        public_metrics: {
        likes: 167,
        reply: 226,
        retweet: 21,
        quote: 59,
        },
        influence: 473,
        geo_location: "Canada",
    },
    {
        id: "070",
        text: "Trump's latest rally draws huge crowds despite recent controversies. Support stronger than ever? #TrumpRally",
        public_metrics: {
        likes: 356,
        reply: 484,
        retweet: 107,
        quote: 36,
        },
        influence: 983,
        geo_location: "Germany",
    },
    {
        id: "071",
        text: "Just saw the latest polls... it's going to be close.",
        public_metrics: {
        likes: 117,
        reply: 193,
        retweet: 22,
        quote: 65,
        },
        influence: 397,
        geo_location: "Brazil",
    },
    {
        id: "072",
        text: "BREAKING: Kamala Harris vows to fight for environmental justice. #Harris2024 #ClimateJustice",
        public_metrics: {
        likes: 69,
        reply: 164,
        retweet: 27,
        quote: 65,
        },
        influence: 325,
        geo_location: "Canada",
    },
    {
        id: "073",
        text: "I'm praying for a peaceful outcome.",
        public_metrics: {
        likes: 272,
        reply: 467,
        retweet: 119,
        quote: 59,
        },
        influence: 917,
        geo_location: "Australia",
    },
    {
        id: "074",
        text: "Rumors swirl about the potential for election fraud in several key states. #Election2024",
        public_metrics: {
        likes: 448,
        reply: 489,
        retweet: 135,
        quote: 86,
        },
        influence: 1158,
        geo_location: "Japan",
    },
    {
        id: "075",
        text: "Record-breaking early voting numbers are being reported nationwide. #Election2024",
        public_metrics: {
        likes: 500,
        reply: 322,
        retweet: 154,
        quote: 61,
        },
        influence: 1037,
        geo_location: "Australia",
    },
    {
        id: "076",
        text: "I really hope we see some positive change.",
        public_metrics: {
        likes: 421,
        reply: 76,
        retweet: 137,
        quote: 9,
        },
        influence: 643,
        geo_location: "Germany",
    },
    {
        id: "077",
        text: "Harris aims to attract young voters with promises of student debt relief. #Harris2024 #StudentDebt",
        public_metrics: {
        likes: 183,
        reply: 423,
        retweet: 27,
        quote: 76,
        },
        influence: 709,
        geo_location: "Brazil",
    },
    {
        id: "078",
        text: "Trump plans to reform the immigration system if re-elected. #Trump2024 #USPolitics",
        public_metrics: {
        likes: 457,
        reply: 12,
        retweet: 15,
        quote: 59,
        },
        influence: 543,
        geo_location: "Brazil",
    },
    {
        id: "079",
        text: "No matter the outcome, let's keep moving forward.",
        public_metrics: {
        likes: 449,
        reply: 33,
        retweet: 88,
        quote: 59,
        },
        influence: 629,
        geo_location: "Canada",
    },
    {
        id: "080",
        text: "FACT CHECK: Rumors about Kamala Harris endorsing mandatory veganism policies are false. #USPolitics #FactCheck",
        public_metrics: {
        likes: 129,
        reply: 121,
        retweet: 72,
        quote: 74,
        },
        influence: 396,
        geo_location: "Germany",
    },
    {
        id: "081",
        text: "New email leaks from the Trump campaign cause uproar ahead of the debates. #TrumpLeaks",
        public_metrics: {
        likes: 77,
        reply: 459,
        retweet: 198,
        quote: 60,
        },
        influence: 794,
        geo_location: "Brazil",
    },
    {
        id: "082",
        text: "Kamala Harris gains momentum with her climate change policies. Could this win over undecided voters? #Harris2024 #ClimateAction",
        public_metrics: {
        likes: 320,
        reply: 367,
        retweet: 148,
        quote: 55,
        },
        influence: 890,
        "geo_location": "Brazil",
    },
    {
        id: "083",
        text: "Is Trump too polarizing to win over moderates? Some analysts believe so. #USPolitics #Trump2024",
        public_metrics: {
        likes: 248,
        reply: 85,
        retweet: 181,
        quote: 93,
        },
        influence: 607,
        "geo_location": "Japan",
    },
    {
        id: "084",
        text: "I just hope the election process is fair and transparent.",
        public_metrics: {
        likes: 160,
        reply: 14,
        retweet: 24,
        quote: 36,
        },
        influence: 234,
        "geo_location": "Australia",
    },
    {
        id: "085",
        text: "Experts warn about the impact of social media disinformation on election integrity. #Disinformation #Election2024",
        public_metrics: {
        likes: 455,
        reply: 287,
        retweet: 21,
        quote: 99,
        },
        influence: 862,
        "geo_location": "Germany",
    },
    {
        id: "086",
        text: "Trump praises supporters for organizing voter turnout initiatives. #TrumpSupporters #Election2024",
        public_metrics: {
        likes: 7,
        reply: 332,
        retweet: 114,
        quote: 74,
        },
        influence: 527,
        "geo_location": "Canada",
    },
    {
        id: "087",
        text: "I wish everyone could stay calm and respect the results.",
        public_metrics: {
        likes: 90,
        reply: 389,
        retweet: 5,
        quote: 26,
        },
        influence: 510,
        "geo_location": "Malaysia",
    },
    {
        id: "088",
        text: "Every vote counts! Make sure yours is counted!",
        public_metrics: {
        likes: 386,
        reply: 119,
        retweet: 39,
        quote: 63,
        },
        influence: 607,
        "geo_location": "India",
    },
    {
        id: "089",
        text: "This election is so close, it's stressing me out.",
        public_metrics: {
        likes: 272,
        reply: 101,
        retweet: 26,
        quote: 57,
        },
        influence: 456,
        "geo_location": "Malaysia",
    },
    {
        id: "090",
        text: "Kamala Harris takes aim at Trump during the debate: 'America deserves better leadership.' #HarrisVsTrump",
        public_metrics: {
        likes: 233,
        reply: 98,
        retweet: 184,
        quote: 60,
        },
        influence: 575,
        "geo_location": "India",
    },
    {
        id: "091",
        text: "FACT CHECK: Kamala Harris did not call for defunding the police in her latest speech. #FactCheck2024 #Harris2024",
        public_metrics: {
        likes: 295,
        reply: 311,
        retweet: 126,
        quote: 88,
        },
        influence: 820,
        "geo_location": "France",
    },
    {
        id: "092",
        text: "No matter who wins, let's hope the country stays united.",
        public_metrics: {
        likes: 174,
        reply: 298,
        retweet: 33,
        quote: 97,
        },
        influence: 602,
        "geo_location": "Australia",
    },
    {
        id: "093",
        text: "Kamala Harris draws sharp contrasts between her policies and Trump's during the town hall. #Election2024",
        public_metrics: {
        likes: 18,
        reply: 394,
        retweet: 181,
        quote: 69,
        },
        influence: 662,
        "geo_location": "Canada",
    },
    {
        id: "094",
        text: "Polls show Trump's base remains fiercely loyal, but is that enough? #Trump2024 #Election2024",
        public_metrics: {
        likes: 174,
        reply: 281,
        retweet: 56,
        quote: 100,
        },
        influence: 611,
        "geo_location": "Germany",
    },
    {
        id: "095",
        text: "Donald Trump says he will fight 'rigged' elections if he loses again. #Election2024 #MAGA",
        public_metrics: {
        likes: 213,
        reply: 14,
        retweet: 2,
        quote: 62,
        },
        influence: 291,
        geo_location: "Brazil",
    },
    {
        id: "096",
        text: "I hope my candidate wins, but I respect the process.",
        public_metrics: {
        likes: 316,
        reply: 135,
        retweet: 165,
        quote: 20,
        },
        influence: 636,
        "geo_location": "Japan",
    },
    {
        id: "097",
        text: "Harris says she will rebuild alliances with key global partners if elected. #Harris2024 #ForeignPolicy",
        public_metrics: {
        likes: 117,
        reply: 271,
        retweet: 55,
        quote: 16,
        },
        influence: 459,
        "geo_location": "Brazil",
    },
    {
        id: "098",
        text: "The voter turnout is incredible this year.",
        public_metrics: {
        likes: 378,
        reply: 24,
        retweet: 61,
        quote: 65,
        },
        influence: 528,
        "geo_location": "Brazil",
    },
    {
        id: "099",
        text: "FACT CHECK: Trump never made the statement about mandatory military service. #FactCheck2024",
        public_metrics: {
        likes: 381,
        reply: 290,
        retweet: 23,
        quote: 45,
        },
        influence: 739,
        "geo_location": "Canada",
    },
    {
        id: "100",
        text: "New voter ID laws spark protests across the country. #VoterRights #Election2024",
        public_metrics: {
        likes: 206,
        reply: 323,
        retweet: 197,
        quote: 35,
        },
        influence: 761,
        "geo_location": "Australia",
    },
    ],
}

export default nodes;
