const postDate = [
  {
    Number: 1,
    Assertions:
      "very long text to test the overflow of the table cell, very long text to test the overflow of the table cell, very long text to test the overflow of the table cell, very long text to test the overflow of the table cell",
    Fact_Check: "False, multiple studies confirm the virus's existence",
    Cross_Reference: "FactCheck.org",
    Source: "Anonymous Source",
    Link: "www.fakecvidhoax.com",
  },
  {
    Number: 2,
    Assertions: "Drinking bleach can cure COVID-19",
    Fact_Check: "False, bleach is harmful and should never be ingested",
    Cross_Reference: "CDC",
    Source: "Misinformation Network",
    Link: "www.drinkbleach.com",
  },
  {
    Number: 3,
    Assertions: "5G technology spreads COVID-19",
    Fact_Check:
      "False, there is no scientific evidence connecting 5G and the virus",
    Cross_Reference: "WHO",
    Source: "Conspiracy Central",
    Link: "www.5gspreadscovid.com",
  },
  {
    Number: 4,
    Assertions: "COVID-19 vaccines contain microchips for tracking",
    Fact_Check: "False, vaccines do not contain any tracking devices",
    Cross_Reference: "NIH",
    Source: "Conspiracy Blog",
    Link: "www.microchipvaccines.com",
  },
  {
    Number: 5,
    Assertions: "COVID-19 was created in a lab as a bioweapon",
    Fact_Check: "False, origins traced to natural sources",
    Cross_Reference: "Nature Journal",
    Source: "Conspiracy Theory Hub",
    Link: "www.labcreatedcovid.com",
  },
  {
    Number: 6,
    Assertions: "Wearing masks is a government control tactic",
    Fact_Check: "False, masks are recommended to protect public health",
    Cross_Reference: "CDC",
    Source: "Misinformation Watch",
    Link: "www.maskcontrol.com",
  },
  {
    Number: 7,
    Assertions: "COVID-19 vaccines can alter your DNA",
    Fact_Check: "False, mRNA vaccines do not change DNA",
    Cross_Reference: "Harvard Health",
    Source: "Health Misinformation Center",
    Link: "www.vaccinealterdna.com",
  },
  {
    Number: 8,
    Assertions: "COVID-19 is just a seasonal flu with a new name",
    Fact_Check: "False, COVID-19 is more severe than the flu",
    Cross_Reference: "WHO",
    Source: "Health Misinformation Blog",
    Link: "www.covidisjustflu.com",
  },
  {
    Number: 9,
    Assertions: "Only elderly people are affected by COVID-19",
    Fact_Check: "False, people of all ages can be infected",
    Cross_Reference: "CDC",
    Source: "False Claims Hub",
    Link: "www.onlyoldpeople.com",
  },
  {
    Number: 10,
    Assertions: "COVID-19 is a plot to control the population",
    Fact_Check: "False, public health measures are to protect communities",
    Cross_Reference: "FactCheck.org",
    Source: "Conspiracy Watch",
    Link: "www.populationcontrolcovid.com",
  },
];

export default postDate;